Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/SimulateToolController.cs
using System;
using System.IO;
using System.Web.Mvc;
using System.Xml.Linq;
using Senparc.Weixin.MP.Agent;
using Senparc.Weixin.MP.Entities;
using Senparc.Weixin.MP.Helpers;

namespace Senparc.Weixin.MP.Sample.Controllers
{
    public class SimulateToolController : BaseController
    {
        /// <summary>
        /// 获取请求XML
        /// </summary>
        /// <returns></returns>
        private XDocument GetrequestMessaageDoc(string url, string token, RequestMsgType requestType, Event? eventType)
        {
            RequestMessageBase requestMessaage = null;
            switch (requestType)
            {
                case RequestMsgType.Text:
                    requestMessaage = new RequestMessageText()
                    {
                        Content = Request.Form["Content"],
                    };
                    break;
                case RequestMsgType.Location:
                    requestMessaage = new RequestMessageLocation()
                    {
                        Label = Request.Form["Label"],
                        Location_X = double.Parse(Request.Form["Location_X"]),
                        Location_Y = double.Parse(Request.Form["Location_Y"]),
                        Scale = int.Parse(Request.Form["Scale"])
                    };
                    break;
                case RequestMsgType.Image:
                    requestMessaage = new RequestMessageImage()
                    {
                        PicUrl = Request.Form["PicUrl"],
                    };
                    break;
                case RequestMsgType.Voice:
                    requestMessaage = new RequestMessageVoice()
                    {
                        Format = Request.Form["Format"],
                        Recognition = Request.Form["Recognition"],
                    };
                    break;
                case RequestMsgType.Video:
                    requestMessaage = new RequestMessageVideo()
                    {
                        MsgId = long.Parse(Request.Form["MsgId"]),
                        ThumbMediaId = Request.Form["ThumbMediaId"],
                    };
                    break;
                //case RequestMsgType.Link:
                //    break;
                case RequestMsgType.Event:
                    if (eventType.HasValue)
                    {
                        RequestMessageEventBase requestMessageEvent = null;
                        switch (eventType.Value)
                        {
                            //case Event.ENTER:
                            //    break;
                            case Event.LOCATION:
                                requestMessageEvent = new RequestMessageEvent_Location()
                                {
                                    Latitude = long.Parse(Request.Form["Event.Latitude"]),
                                    Longitude = long.Parse(Request.Form["Event.Longitude"]),
                                    Precision = double.Parse(Request.Form["Event.Precision"])
                                };
                                break;
                            case Event.subscribe:
                                requestMessageEvent = new RequestMessageEvent_Subscribe()
                                {
                                    EventKey = Request.Form["Event.EventKey"]
                                };
                                break;
                            case Event.unsubscribe:
                                requestMessageEvent = new RequestMessageEvent_Unsubscribe();
                                break;
                            case Event.CLICK:
                                requestMessageEvent = new RequestMessageEvent_Click()
                                   {
                                       EventKey = Request.Form["Event.EventKey"]
                                   };
                                break;
                            case Event.scan:
                                requestMessageEvent = new RequestMessageEvent_Scan()
                                 {
                                     EventKey = Request.Form["Event.EventKey"],
                                     Ticket = Request.Form["Event.Ticket"]
                                 }; break;
                            case Event.VIEW:
                                requestMessageEvent = new RequestMessageEvent_View()
                                 {
                                     EventKey = Request.Form["Event.EventKey"]
                                 }; break;
                            case Event.MASSSENDJOBFINISH:
                                requestMessageEvent = new RequestMessageEvent_MassSendJobFinish()
                                {
                                    FromUserName = "mphelper",//系统指定
                                    ErrorCount = int.Parse(Request.Form["Event.ErrorCount"]),
                                    FilterCount = int.Parse(Request.Form["Event.FilterCount"]),
                                    SendCount = int.Parse(Request.Form["Event.SendCount"]),
                                    Status = Request.Form["Event.Status"],
                                    TotalCount = int.Parse(Request.Form["Event.TotalCount"])
                                }; break;
                            default:
                                throw new ArgumentOutOfRangeException("eventType");
                        }
                        requestMessaage = requestMessageEvent;
                    }
                    else
                    {
                        throw new ArgumentOutOfRangeException("eventType");
                    }
                    break;
                default:
                    throw new ArgumentOutOfRangeException("requestType");
            }
            requestMessaage.MsgId = long.Parse(Request.Form["MsgId"]);
            requestMessaage.CreateTime = DateTime.Now;
            requestMessaage.FromUserName = requestMessaage.FromUserName ?? "FromUserName（OpenId）";//用于区别不同的请求用户
            requestMessaage.ToUserName = "ToUserName";

            return requestMessaage.ConvertEntityToXml();
        }

        /// <summary>
        /// 默认页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewData["Token"] = WeixinController.Token;
            return View();
        }

        /// <summary>
        /// 模拟发送并返回结果
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(string url, string token, RequestMsgType requestType, Event? eventType)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                var requestMessaageDoc = GetrequestMessaageDoc(url, token, requestType, eventType);
                requestMessaageDoc.Save(ms);
                ms.Seek(0, SeekOrigin.Begin);

                var responseMessageXml = MessageAgent.RequestXml(null, url, token, requestMessaageDoc.ToString());

                if (string.IsNullOrEmpty(responseMessageXml))
                {
                    responseMessageXml = "返回消息为空，可能已经被去重。\r\nMsgId相同的连续消息将被自动去重。";
                }

                return Content(responseMessageXml);
            }
        }

        /// <summary>
        /// 返回模拟发送的XML
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetRequestMessageXml(string url, string token, RequestMsgType requestType, Event? eventType)
        {
            var requestMessaageDoc = GetrequestMessaageDoc(url, token, requestType, eventType);
            return Content(requestMessaageDoc.ToString());
        }
    }
}

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/WeixinController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using Senparc.Weixin.MP.Entities.Request;

namespace Senparc.Weixin.MP.Sample.Controllers
{
    using Senparc.Weixin.MP.MessageHandlers;
    using Senparc.Weixin.MP.Entities;
    using Senparc.Weixin.MP.Helpers;
    using Senparc.Weixin.MP.MvcExtension;
    //using Senparc.Weixin.MP.Sample.Service;
    //using Senparc.Weixin.MP.Sample.CustomerMessageHandler;
    using Senparc.Weixin.MP.Sample.CommonService;
    using Senparc.Weixin.MP.Sample.CommonService.CustomMessageHandler;

    public partial class WeixinController : Controller
    {
        public static readonly string Token = "weixin";//与微信公众账号后台的Token设置保持一致，区分大小写。

        public WeixinController()
        {

        }

        /// <summary>
        /// 微信后台验证地址（使用Get），微信后台的“接口配置信息”的Url填写如：http://weixin.senparc.com/weixin
        /// </summary>
        [HttpGet]
        [ActionName("Index")]
        public ActionResult Get(string signature, string timestamp, string nonce, string echostr)
        {
            if (CheckSignature.Check(signature, timestamp, nonce, Token))
            {
                return Content(echostr); //返回随机字符串则表示验证通过
            }
            else
            {
                return Content("failed:" + signature + "," + MP.CheckSignature.GetSignature(timestamp, nonce, Token) + "。" +
                    "如果你在浏览器中看到这句话，说明此地址可以被作为微信公众账号后台的Url，请注意保持Token一致。");
            }
        }

        /// <summary>
        /// 用户发送消息后，微信平台自动Post一个请求到这里，并等待响应XML。
        /// PS：此方法为简化方法，效果与OldPost一致。
        /// v0.8之后的版本可以结合Senparc.Weixin.MP.MvcExtension扩展包，使用WeixinResult，见MiniPost方法。
        /// </summary>
        [HttpPost]
        [ActionName("Index")]
        public ActionResult Post(PostModel postModel)
        {
            if (!CheckSignature.Check(postModel.Signature, postModel.Timestamp, postModel.Nonce, Token))
            {
                return Content("参数错误！");
            }

            postModel.Token = Token;
            postModel.EncodingAESKey = "YTJkZmVjMzQ5NDU5NDY3MDhiZWI0NTdiMjFiY2I5MmU";//根据自己后台的设置保持一致
            postModel.AppId = "wx669ef95216eef885";//根据自己后台的设置保持一致

            //v4.2.2之后的版本，可以设置每个人上下文消息储存的最大数量，防止内存占用过多，如果该参数小于等于0，则不限制
            var maxRecordCount = 10;

            //自定义MessageHandler，对微信请求的详细判断操作都在这里面。
            var messageHandler = new CustomMessageHandler(Request.InputStream, postModel, maxRecordCount);

            try
            {
                //测试时可开启此记录，帮助跟踪数据，使用前请确保App_Data文件夹存在，且有读写权限。
                messageHandler.RequestDocument.Save(Server.MapPath("~/App_Data/" + DateTime.Now.Ticks + "_Request_" + messageHandler.RequestMessage.FromUserName + ".txt"));
                if (messageHandler.UsingEcryptMessage)
                {
                    messageHandler.EcryptRequestDocument.Save(Server.MapPath("~/App_Data/" + DateTime.Now.Ticks + "_Request_Ecrypt_" + messageHandler.RequestMessage.FromUserName + ".txt"));
                }

                /* 如果需要添加消息去重功能，只需打开OmitRepeatedMessage功能，SDK会自动处理。
                 * 收到重复消息通常是因为微信服务器没有及时收到响应，会持续发送2-5条不等的相同内容的RequestMessage*/
                messageHandler.OmitRepeatedMessage = true;

                //执行微信处理过程
                messageHandler.Execute();

                //测试时可开启，帮助跟踪数据
                messageHandler.ResponseDocument.Save(Server.MapPath("~/App_Data/" + DateTime.Now.Ticks + "_Response_" + messageHandler.ResponseMessage.ToUserName + ".txt"));
                if (messageHandler.UsingEcryptMessage)
                {
                    //记录加密后的响应信息
                    messageHandler.FinalResponseDocument.Save(Server.MapPath("~/App_Data/" + DateTime.Now.Ticks + "_Response_Final_" + messageHandler.ResponseMessage.ToUserName + ".txt"));
                }

                //return Content(messageHandler.ResponseDocument.ToString());//v0.7-
                return new FixWeixinBugWeixinResult(messageHandler);//为了解决官方微信5.0软件换行bug暂时添加的方法，平时用下面一个方法即可
                //return new WeixinResult(messageHandler);//v0.8+
            }
            catch (Exception ex)
            {
                using (TextWriter tw = new StreamWriter(Server.MapPath("~/App_Data/Error_" + DateTime.Now.Ticks + ".txt")))
                {
                    tw.WriteLine("ExecptionMessage:" + ex.Message);
                    tw.WriteLine(ex.Source);
                    tw.WriteLine(ex.StackTrace);
                    //tw.WriteLine("InnerExecptionMessage:" + ex.InnerException.Message);

                    if (messageHandler.ResponseDocument != null)
                    {
                        tw.WriteLine(messageHandler.ResponseDocument.ToString());
                    }
                    tw.Flush();
                    tw.Close();
                }
                return Content("");
            }
        }


        /// <summary>
        /// 最简化的处理流程（不加密）
        /// </summary>
        [HttpPost]
        [ActionName("MiniPost")]
        public ActionResult MiniPost(string signature, string timestamp, string nonce, string echostr)
        {
            if (!CheckSignature.Check(signature, timestamp, nonce, Token))
            {
                //return Content("参数错误！");//v0.7-
                return new WeixinResult("参数错误！");//v0.8+
            }

            var messageHandler = new CustomMessageHandler(Request.InputStream, null, 10);

            messageHandler.Execute();//执行微信处理过程

            //return Content(messageHandler.ResponseDocument.ToString());//v0.7-
            return new FixWeixinBugWeixinResult(messageHandler);//v0.8+
            return new WeixinResult(messageHandler);//v0.8+
        }

        /*
         * v0.3.0之前的原始Post方法见：WeixinController_OldPost.cs
         * 
         * 注意：虽然这里提倡使用CustomerMessageHandler的方法，但是MessageHandler基类最终还是基于OldPost的判断逻辑，
         * 因此如果需要深入了解Senparc.Weixin.MP内部处理消息的机制，可以查看WeixinController_OldPost.cs中的OldPost方法。
         * 目前为止OldPost依然有效，依然可用于生产。
         */
    }
}

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/SimulateTool/Index.cshtml
@{
    ViewBag.Title = "微信消息模拟测试工具";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var nonce = "JeffreySu";
    var timestamp = DateTime.Now.Ticks.ToString();
    var echostr = DateTime.Now.Ticks.ToString();
    var token = ViewData["Token"] as string;
}
@section HeaderContent
{
    <style>
        .param {
            display: none;
        }

        .messageXmlArea {
            width: 100%;
        }

            .messageXmlArea textarea {
                width: 100%;
                height: 200px;
            }

        .paramAreaLeft {
            float: left;
            width: 45%;
            margin-right: 6%;
        }

        .paramArearight {
            width: 45%;
            float: left;
        }

        #requestType, #eventType {
            padding: 5px;
        }
    </style>
    <script>
        $(function () {
            $('#requestType').change(checkRequestType);
            $('#eventType').change(checkEventType);
            checkRequestType();
            checkEventType();
        });

        function checkRequestType() {
            var requestType = $('#requestType').val();
            var paramId = 'param' + requestType;
            $('div[id^=param]').hide();
            $('#' + paramId).show();
        }

        function checkEventType() {
            var requestType = $('#eventType').val();
            var eventId = 'event' + requestType;
            $('div[id^=event]').hide();
            $('#' + eventId).show();
        }

        function sendMessage() {
            var url = $('#Url').val();
            var token = $('#Token').val();
            var requestType = $('#requestType').val();
            var eventType = $('#eventType').val();
            var param = { url: url, token: token, requestType: requestType };
            var paramId = 'param' + requestType;
            var eventId = 'event' + eventType;
            var msgId = $('#txtMsgId').val();

            if (!msgId) {
                alert('MsgId必须填写！');
                return;
            }

            //设置参数
            if (requestType != 'Event') {
                $.each($('#' + paramId).find('input'), function (i, item) {
                    param[$(item).attr('name')] = $(item).val();
                });
            } else {
                param.eventType = eventType;
                $.each($('#' + eventId).find('input'), function (i, item) {
                    param[$(item).attr('name')] = $(item).val();
                });
            }
            param.MsgId = msgId;
            
            var txtResponseMessageXML = $('#responseMessageXML');
            var txtRequestMessageXML = $('#requestMessageXML');

            txtResponseMessageXML.html('载入中...');
            txtRequestMessageXML.html('载入中...');

            $.post('@Url.Action("Index")', param, function (result) {
                txtResponseMessageXML.text(result);
            });

            $.post('@Url.Action("GetRequestMessageXml")', param, function (result) {
                txtRequestMessageXML.text(result);
            });
        }
    </script>
}
@section Featured
{

}
<section class="content-wrapper main-content clear-fix">
    <h1>消息模拟工具</h1>
    <div class="clear-fix"></div>
    <div id="simulateTool">
        <div class="paramAreaLeft">
            <h3>接口设置</h3>
            <div>
                URL：@Html.TextBox("Url", Url.Action("Index", "Weixin", null, "http", Request.Url.Host))<br />
                Token：@Html.TextBox("Token", token)
            </div>
            <h3>发送参数</h3>
            <div>
                类型：<select id="requestType">
                    <option value="Text">文本</option>
                    <option value="Location">地理位置</option>
                    <option value="Image">图片</option>
                    <option value="Voice">语音</option>
                    <option value="Video">视频</option>
                    @*<option value="Link">连接信息</option>*@
                    <option value="Event">事件推送</option>
                </select>
            </div>
            <div>
                参数：
                <div id="paramText" class="param">
                    Content：<input name="Content" />
                </div>
                <div id="paramLocation" class="param">
                    Label：<input name="Label" /><br />
                    Location_X：<input name="Location_X" type="number" value="0" /><br />
                    Location_Y：<input name="Location_Y" type="number" value="0" /><br />
                    Scale：<input name="Scale" type="number" value="0" step="1" /><br />
                </div>
                <div id="paramImage" class="param">
                    PicUrl：<input name="PicUrl" /><br />
                </div>
                <div id="paramVoice" class="param">
                    Format：<input name="Format" value="arm" /><br />
                    Recognition：<input name="Recognition" /><br />
                </div>
                <div id="paramVideo" class="param">
                    MsgId：<input name="MsgId" type="number" value="@DateTime.Now.Ticks" step="1" /><br />
                    ThumbMediaId：<input name="ThumbMediaId" /><br />
                </div>
                @*<div id="paramLink" class="param"></div>*@
                <div id="paramEvent" class="param">
                    事件类型：<select id="eventType">
                        @*<option value="ENTER">进入会话</option>*@
                        <option value="LOCATION">地理位置</option>
                        <option value="subscribe">订阅</option>
                        <option value="unsubscribe">取消订阅</option>
                        <option value="CLICK">自定义菜单点击事件</option>
                        <option value="scan">二维码扫描</option>
                        <option value="VIEW">URL跳转</option>
                        <option value="MASSSENDJOBFINISH">事件推送群发结果</option>
                    </select>
                    @*<div id="eventENTER" class="param"></div>*@
                    <div id="eventLOCATION" class="param">
                        Latitude：<input name="Event.Latitude" type="number" value="0"/><br />
                        Longitude：<input name="Event.Longitude" type="number" value="0"/><br />
                        Precision：<input name="Event.Precision" type="number" value="0"/><br />
                    </div>
                    <div id="eventsubscribe" class="param">
                        EventKey：<input name="Event.EventKey" /><br />
                    </div>
                    <div id="eventunsubscribe" class="param"></div>
                    <div id="eventCLICK" class="param">
                        EventKey：<input name="Event.EventKey" /><br />
                    </div>
                    <div id="eventscan" class="param">
                        EventKey：<input name="Event.EventKey" /><br />
                        Ticket：<input name="Event.Ticket" /><br />
                    </div>
                    <div id="eventVIEW" class="param">
                        EventKey：<input name="Event.EventKey" value="http://" /><br />
                    </div>
                    <div id="eventMASSSENDJOBFINISH" class="param">
                        ErrorCount：<input name="Event.ErrorCount" type="number" value="0"/><br />
                        FilterCount：<input name="Event.FilterCount" type="number" value="0"/><br />
                        SendCount：<input name="Event.SendCount" type="number" value="0"/><br />
                        Status：<input name="Event.Status"/><br />
                        TotalCount：<input name="Event.TotalCount" type="number" value="0"/><br />
                    </div>
                    
                </div>
                <div>
                    <div>
                        MsgId：<input id="txtMsgId" name="MsgId" type="number" value="@DateTime.Now.Ticks" /><br />
                    </div>
                   
                    <input type="button" value="提交" onclick="sendMessage()" />
                </div>
            </div>
        </div>
        <div class="paramArearight">

            <div class="messageXmlArea">
                <h3>发送内容（根据参数自动生成）</h3>
                <textarea id="requestMessageXML" readonly="readonly"></textarea>
            </div>
            <div class="messageXmlArea">
                <h3>接收内容</h3>
                <textarea id="responseMessageXML"></textarea>
            </div>
        </div>
    </div>
</section>