Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml.Linq;
using Senparc.Weixin.MP.AdvancedAPIs;
using Senparc.Weixin.MP.CommonAPIs;
using Senparc.Weixin.MP.Entities;
using Senparc.Weixin.MP.TenPayLibV3;

namespace Senparc.Weixin.MP.Sample.Controllers
{
    /// <summary>
    /// 根据官方的Webforms Demo改写，所以可以看到直接Response.Write()之类的用法，实际项目中不提倡这么做。
    /// </summary>
    public class TenPayV3Controller : Controller
    {
        private static TenPayV3Info _tenPayV3Info;

        public static TenPayV3Info TenPayV3Info
        {
            get
            {
                if (_tenPayV3Info == null)
                {
                    _tenPayV3Info =
                        TenPayV3InfoCollection.Data[System.Configuration.ConfigurationManager.AppSettings["TenPayV3_MchId"]];
                }
                return _tenPayV3Info;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取用户的OpenId
        /// </summary>
        /// <returns></returns>
        public ActionResult GetOpenId()
        {
            ViewData["UrlUserInfo"] = OAuth.GetAuthorizeUrl(TenPayV3Info.AppId, "http://weixin.senparc.com/TenPayV3/JsApi", "JeffreySu", OAuthScope.snsapi_userinfo);

            return View();
        }

        public ActionResult JsApi(string code, string state)
        {
            if (string.IsNullOrEmpty(code))
            {
                return Content("您拒绝了授权！");
            }

            if (state != "JeffreySu")
            {
                //这里的state其实是会暴露给客户端的，验证能力很弱，这里只是演示一下
                //实际上可以存任何想传递的数据，比如用户ID，并且需要结合例如下面的Session["OAuthAccessToken"]进行验证
                return Content("验证失败！请从正规途径进入！");
            }

            //通过，用code换取access_token
            var openIdResult = OAuth.GetAccessToken(TenPayV3Info.AppId, TenPayV3Info.AppSecret, code);
            if (openIdResult.errcode != ReturnCode.请求成功)
            {
                return Content("错误：" + openIdResult.errmsg);
            }

            string timeStamp = "";
            string nonceStr = "";
            string paySign = "";

            string sp_billno = Request["order_no"];
            //当前时间 yyyyMMdd
            string date = DateTime.Now.ToString("yyyyMMdd");

            if (null == sp_billno)
            {
                //生成订单10位序列号，此处用时间和随机数生成，商户根据自己调整，保证唯一
                sp_billno = DateTime.Now.ToString("HHmmss") + TenPayUtil.BuildRandomStr(28);
            }
            else
            {
                sp_billno = Request["order_no"].ToString();
            }

            //创建支付应答对象
            RequestHandler packageReqHandler = new RequestHandler(null);
            //初始化
            packageReqHandler.Init();
            //packageReqHandler.SetKey(""/*TenPayV3Info.Key*/);

            timeStamp = TenPayUtil.GetTimestamp();
            nonceStr = TenPayUtil.GetNoncestr();

            //设置package订单参数
            packageReqHandler.SetParameter("appid", TenPayV3Info.AppId);		  //公众账号ID
            packageReqHandler.SetParameter("mch_id", TenPayV3Info.MchId);		  //商户号
            packageReqHandler.SetParameter("nonce_str", nonceStr);                    //随机字符串
            packageReqHandler.SetParameter("body", "test");
            packageReqHandler.SetParameter("out_trade_no", sp_billno);		//商家订单号
            packageReqHandler.SetParameter("total_fee", "1");			        //商品金额,以分为单位(money * 100).ToString()
            packageReqHandler.SetParameter("spbill_create_ip", Request.UserHostAddress);   //用户的公网ip，不是商户服务器IP
            packageReqHandler.SetParameter("notify_url", TenPayV3Info.TenPayV3Notify);		    //接收财付通通知的URL
            packageReqHandler.SetParameter("trade_type", TenPayV3Type.JSAPI.ToString());	                    //交易类型
            packageReqHandler.SetParameter("openid", openIdResult.openid);	                    //用户的openId

            string sign = packageReqHandler.CreateMd5Sign("key", TenPayV3Info.Key);
            packageReqHandler.SetParameter("sign", sign);	                    //签名

            string data = packageReqHandler.ParseXML();

            var result = TenPayV3.Unifiedorder(data);
            var res = XDocument.Parse(result);
            string prepayId = res.Element("xml").Element("prepay_id").Value;

            //设置支付参数
            RequestHandler paySignReqHandler = new RequestHandler(null);
            paySignReqHandler.SetParameter("appId", TenPayV3Info.AppId);
            paySignReqHandler.SetParameter("timeStamp", timeStamp);
            paySignReqHandler.SetParameter("nonceStr", nonceStr);
            paySignReqHandler.SetParameter("package", string.Format("prepay_id={0}", prepayId));
            paySignReqHandler.SetParameter("signType", "MD5");
            paySign = paySignReqHandler.CreateMd5Sign("key", TenPayV3Info.Key);

            ViewData["appId"] = TenPayV3Info.AppId;
            ViewData["timeStamp"] = timeStamp;
            ViewData["nonceStr"] = nonceStr;
            ViewData["package"] = string.Format("prepay_id={0}", prepayId);
            ViewData["paySign"] = paySign;

            return View();
        }

        public ActionResult PayNotifyUrl()
        {
            var fileStream = System.IO.File.OpenWrite(Server.MapPath("~/1.txt"));
            var bytes = Encoding.UTF8.GetBytes(Request.InputStream.ToString());
            fileStream.Write(bytes, 0, bytes.Length);
            fileStream.Close();
            return Content("");
        }
    }
}

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/GetOpenId.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>测试snsapi_userinfo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script language="javascript" src="http://res.mail.qq.com/mmr/static/lib/js/jquery.js" type="text/javascript"></script>
    <script language="javascript" src="http://res.mail.qq.com/mmr/static/lib/js/lazyloadv3.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
</head>
<body>
    <div>
        <p><a href="@ViewData["UrlUserInfo"]">点击这里测试snsapi_userinfo</a></p>
        <p>
            将要链接到的地址：<br />
            <textarea rows="10" cols="40">@ViewData["UrlUserInfo"]</textarea>
        </p>
    </div>
</body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
        <title>微信支付测试跳转页</title>

    </head>
    <body>
        <div>
            <a href="@Url.Action("GetOpenId","TenPayV3")">获取OpenId</a>
        </div>
    </body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/JsApi.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>公众号jsapi支付测试网页</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script language="javascript" src="http://res.mail.qq.com/mmr/static/lib/js/jquery.js" type="text/javascript"></script>
    <script language="javascript" src="http://res.mail.qq.com/mmr/static/lib/js/lazyloadv3.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }


        .container {
        }

        .title {
        }

        #content {
            padding: 30px 20px 20px;
            color: #111;
            background: #f7f2ed;
        }

        .seeAlso {
            padding: 15px 20px 30px;
        }

        .headpic div {
            margin: 20px 0 0;
        }

        .headpic img {
            display: block;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

        .pic {
            margin: 20px 0;
        }

        .articlecontent img {
            display: block;
            clear: both;
            margin: 5px auto;
        }

        .articlecontent p {
            text-indent: 2em;
            font-family: Georgia,helvetica,Arial,Tahoma;
            line-height: 1.4;
            font-size: 16px;
            margin: 20px 0;
        }


        .seeAlso h3 {
            font-size: 16px;
            color: #a5a5a5;
        }

        .seeAlso ul {
            margin: 0;
            padding: 0;
        }

        .seeAlso li {
            font-size: 16px;
            list-style-type: none;
            border-top: 1px solid #ccc;
            padding: 2px 0;
        }

            .seeAlso li a {
                border-bottom: none;
                display: block;
                line-height: 1.1;
                padding: 13px 0;
            }

        .clr {
            clear: both;
            height: 1px;
            overflow: hidden;
        }


        .fontSize1 .title h1 {
            font-size: 20px;
        }

        .fontSize1 .articlecontent p {
            font-size: 14px;
        }

        .fontSize1 .weibo .nickname, .fontSize1 .weibo .comment {
            font-size: 11px;
        }

        .fontSize1 .moreOperator {
            font-size: 14px;
        }

        .fontSize2 .title h1 {
            font-size: 22px;
        }

        .fontSize2 .articlecontent p {
            font-size: 16px;
        }

        .fontSize2 .weibo .nickname, .fontSize2 .weibo .comment {
            font-size: 13px;
        }

        .fontSize2 .moreOperator {
            font-size: 16px;
        }

        .fontSize3 .title h1 {
            font-size: 24px;
        }

        .fontSize3 .articlecontent p {
            font-size: 18px;
        }

        .fontSize3 .weibo .nickname, .fontSize3 .weibo .comment {
            font-size: 15px;
        }

        .fontSize3 .moreOperator {
            font-size: 18px;
        }

        .fontSize4 .title h1 {
            font-size: 26px;
        }

        .fontSize4 .articlecontent p {
            font-size: 20px;
        }

        .fontSize4 .weibo .nickname, .fontSize4 .weibo .comment {
            font-size: 16px;
        }

        .fontSize4 .moreOperator {
            font-size: 20px;
        }

        .jumptoorg {
            display: block;
            margin: 16px 0 16px;
        }

            .jumptoorg a {
            }

        .moreOperator a {
            color: #385487;
        }

        .moreOperator .share {
            border-top: 1px solid #ddd;
        }

            .moreOperator .share a {
                display: block;
                border: 1px solid #ccc;
                border-bottom-style: solid;
                background: #f8f7f1;
                color: #000;
            }

                .moreOperator .share a span {
                    display: block;
                    padding: 10px 10px;
                    text-align: center;
                    border-top: 1px solid #eee;
                    border-bottom: 1px solid #eae9e3;
                    font-weight: bold;
                }

                .moreOperator .share a:hover,
                .moreOperator .share a:active {
                    background: #efedea;
                }

        @@media only screen and (-webkit-min-device-pixel-ratio: 2) {
        }
    </style>
    <script language="javascript" type="text/javascript">
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        // 当微信内置浏览器完成内部初始化后会触发WeixinJSBridgeReady事件。
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            //公众号支付
            jQuery('a#getBrandWCPayRequest').click(function (e) {
                WeixinJSBridge.invoke('getBrandWCPayRequest', {
                    "appId": "@ViewData["appId"]", //公众号名称，由商户传入
                    "timeStamp": "@ViewData["timeStamp"]", //时间戳
                    "nonceStr": "@ViewData["nonceStr"]", //随机串
                    "package": "@Html.Raw(ViewData["package"])",//扩展包
                    "signType": "MD5", //微信签名方式:1.sha1
                    "paySign": "@ViewData["paySign"]" //微信签名
                }, function (res) {

                    if (res.err_msg == "get_brand_wcpay_request:ok") {
                    }
                    // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回ok，但并不保证它绝对可靠。
                    //因此微信团队建议，当收到ok返回时，向商户后台询问是否收到交易成功的通知，若收到通知，前端展示交易成功的界面；若此时未收到通知，商户后台主动调用查询订单接口，查询订单的当前状态，并反馈给前端展示相应的界面。
                });

            });

            WeixinJSBridge.log('yo~ ready.');

        }, false);
        if (jQuery) {
            jQuery(function () {

                var width = jQuery('body').width() * 0.87;
                jQuery('img').error(function () {
                    var self = jQuery(this);
                    var org = self.attr('data-original1');
                    self.attr("src", org);
                    self.error(function () {
                        auto_remove(this);
                    });
                });
                jQuery('img').each(function () {
                    var self = jQuery(this);
                    var w = self.css('width');
                    var h = self.css('height');
                    w = w.replace('px', '');
                    h = h.replace('px', '');
                    if (w <= width) {
                        return;
                    }
                    var new_w = width;
                    var new_h = Math.round(h * width / w);
                    self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                    self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                });
            });
        }
    </script>
</head>
<body>
    <div class="WCPay">
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            <h1 class="title">点击提交可体验微信支付</h1>
        </a>

    </div>
</body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/PayNotifyUrl.cshtml
@{
    Layout = null;
}

<html>
<head>
    <title>PayNotifyUrl</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    </form>
</body>
</html>